# Generated by Django 5.1.1 on 2024-10-12 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_rename_fecha_pedido_pedido_fecha_alter_pedido_total_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='estado',
        ),
    ]
