# Generated by Django 5.1.1 on 2024-10-12 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_remove_pedido_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='estado',
            field=models.CharField(default='Pendiente', max_length=20),
        ),
    ]
