# Generated by Django 5.1.2 on 2024-10-14 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_alter_pedido_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('en_espera', 'En Espera'), ('en_proceso', 'En Proceso'), ('finalizado', 'Finalizado'), ('rechazado', 'Rechazado'), ('listo', 'Listo para enviar'), ('enviado', 'Enviado')], default='Pendiente', max_length=20),
        ),
    ]
