# Generated by Django 5.1.2 on 2024-10-15 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_alter_pedido_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='tiempo_preparacion',
            field=models.IntegerField(default=0),
        ),
    ]
