# Generated by Django 5.1.2 on 2024-10-16 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_oferta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='foto',
            field=models.ImageField(default='productos/perfil.webp', upload_to='perfil_fotos/'),
        ),
    ]
