# Generated by Django 5.1.3 on 2024-11-16 10:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0028_alter_pedido_usuario"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="pedido",
            name="estado",
            field=models.CharField(
                choices=[
                    ("en_espera", "En Espera"),
                    ("en_proceso", "En Proceso"),
                    ("finalizado", "Finalizado"),
                    ("rechazado", "Rechazado"),
                    ("listo", "Listo para enviar"),
                    ("enviado", "Enviado"),
                ],
                default="en_espera",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="pedido",
            name="usuario",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
