# Generated by Django 5.1.3 on 2024-11-16 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0030_pedido_invitado_id_alter_pedido_usuario"),
    ]

    operations = [
        migrations.AddField(
            model_name="pedido",
            name="metodo_pago",
            field=models.CharField(
                choices=[
                    ("credit_card", "Tarjeta de Crédito"),
                    ("debit_card", "Tarjeta de Débito"),
                    ("paypal", "PayPal"),
                ],
                default="credit_card",
                max_length=20,
            ),
        ),
    ]
