# Generated by Django 5.1.2 on 2024-11-18 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0035_alter_profile_foto"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="foto",
            field=models.ImageField(
                default="perfil_fotos/avatar.webp", upload_to="perfil_fotos/"
            ),
        ),
    ]
