# Generated by Django 5.1.2 on 2024-11-19 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0036_alter_profile_foto"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="foto",
            field=models.ImageField(
                default="media/media/perfil_fotos/avatar.webp",
                upload_to="perfil_fotos/",
            ),
        ),
    ]
