# Generated by Django 4.2.16 on 2024-11-25 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0041_producto_activo_producto_imagen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='subcategoria',
            field=models.CharField(default='sin_subcategoria', max_length=100),
        ),
    ]
