# Generated by Django 5.1.4 on 2024-12-05 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0043_sugerencia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sugerencia',
            name='fecha',
        ),
        migrations.AlterField(
            model_name='sugerencia',
            name='usuario',
            field=models.CharField(max_length=150),
        ),
    ]
