# Generated by Django 5.1.3 on 2024-12-08 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0044_remove_sugerencia_fecha_alter_sugerencia_usuario"),
    ]

    operations = [
        migrations.AddField(
            model_name="producto",
            name="alergenos",
            field=models.TextField(blank=True, null=True),
        ),
    ]
