# Generated by Django 5.1.3 on 2024-12-08 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0045_producto_alergenos"),
    ]

    operations = [
        migrations.AddField(
            model_name="producto",
            name="visibilidad",
            field=models.CharField(
                choices=[
                    ("ambos", "Ambos"),
                    ("carta", "Solo en la Carta"),
                    ("principal", "Solo en la Página Principal"),
                ],
                default="ambos",
                max_length=10,
            ),
        ),
    ]
