# Generated by Django 5.1.3 on 2024-12-08 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0047_rename_activo_producto_activo_carta_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="producto",
            old_name="activo_carta",
            new_name="activo",
        ),
        migrations.RemoveField(
            model_name="producto",
            name="activo_principal",
        ),
        migrations.RemoveField(
            model_name="producto",
            name="visibilidad",
        ),
    ]
